---
# Handlers for vault_server role

- name: Restart Vault
  ansible.builtin.service:
    name: vault
    state: restarted

- name: Reload Vault
  ansible.builtin.service:
    name: vault
    state: reloaded