---
# roles/nexus/defaults/main.yml

# VersiÃ³n de Nexus
nexus_version: "3.70.1"

# ğŸ“¡ ConfiguraciÃ³n NAS
nexus_nas_ip: "10.0.0.5"
nexus_nas_path: "/mnt/HD/HD_a2/nexus_data"

# ğŸ“‚ Punto de montaje local (Este ya te funciona)
nexus_mount_point: "/mnt/nexus_data"

# ğŸ³ ConfiguraciÃ³n del contenedor Nexus
nexus_image: "sonatype/nexus3:{{ nexus_version }}"
nexus_container_name: "nexus-server"
nexus_memory_limit: "5g"

# ğŸ†” Mapeo de Usuario NAS (CosmÃ©tico)
# Define quÃ© ID usa tu NAS para que Linux sepa ponerle nombre
nexus_nas_uid: 501
nexus_nas_gid: 1000
nexus_nas_user: "nas-admin"